version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-zenrows}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro

volumes: {}
